<link rel="stylesheet" href="${pageContext.request.contextPath}/plugins/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/static/css/register-form.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/plugins/alertifyjs/css/alertify.min.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/plugins/alertifyjs/css/themes/bootstrap.min.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/plugins/datatables/datatables.min.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/plugins/datatables/buttons/css/buttons.dataTables.min.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/plugins/angular-xeditable/css/bootstrap-editable.css"/>
<link rel="stylesheet" href="${pageContext.request.contextPath}/plugins/angular-xeditable/css/xeditable.min.css"/>
<link rel="stylesheet" href="${pageContext.request.contextPath}/plugins/jqueryui/jquery-ui.theme.min.css"/>
<link rel="stylesheet" href="${pageContext.request.contextPath}/plugins/select2/css/select2.min.css"/>
